### ISSUE TITLE
NULL returned in EmtpyElementsFilter

### ISSUE THREAD

**Issue by duesterTechnology** [templado/engine#10]
The class EmptyElementsFilter returns NULL in case something went wrong in preg_replace()-fkt. I have no example yet. I think at least an exception should be thrown within the 'apply'-fkt. in case of an error in the preg_replace()-fkt. This results in an empty string in the 'asString()'-fkt. of the Html class

Best,
Tobi

**Comment by duesterTechnology** [comment]
Found that the error in preg_replace was an PREG_BACKTRACK_LIMIT_ERROR

Seems that the amount of data I have is too high - I had to set the pcre.backtrack_lomit to 10.000.000

**Comment by theseer** [comment]
Nice catch. I'm not sure though I want to understand how you managed to reach that limit ;)

**Comment by duesterTechnology** [comment]
I have lots of data in table ... I think I will have to split the data to avoid such limits. Which means the string for preg_replace is very large but not the replacements it performs ... how could this happen

**Comment by theseer** [comment]
Fixed in 2.3.1+

**Comment by theseer** [comment]
I cannot come up with a "smarter" regex that would work with a lower back tracking overhead.

But at least we get a proper exception now in case it exceeds the configured limit.
