### ISSUE TITLE
Problems with multiple properties

### ISSUE THREAD

**Issue by duesterTechnology** [templado/engine#2]
Hi Arne,

I have a small problem when I try to use Templado engine with the following html part:

```
<html>
<head>
    <title>Title</title>
</head>
<body>

    <ul property="list">
        <li property="entry">
            <span property="entry1"></span>
            <span property="entry2"></span>
        </li>
    </ul>
</body>
</html>
```

Depending on the object that fills the li-property 'entry' the function to handle 'entry1' returns false and the one for 'entry2' returns a string or the other way around. 
So there are two functions in each class that can fill a li-property 'entry'. 

So what I expected was something like this:

```
<html>
  <head>
    <title>Title</title>
  </head>
  <body>
    <ul property="list">
      <li property="entry">
        <span property="entry1">Entry1</span>
      </li>
      <li property="entry">
        <span property="entry2">Entry2</span>
      </li>
      <li property="entry">
        <span property="entry1">Entry1</span>
      </li>
    </ul>
  </body>
</html>
```

However, the result looks like this:

```
<html>
  <head>
    <title>Title</title>
  </head>
  <body>
    <ul property="list">
      <li property="entry">
        <span property="entry1">Entry1</span>
      </li>
      <li property="entry">
        <span property="entry2"></span>
      </li>
      <li property="entry">
        <span property="entry1">Entry1</span>
      </li>
    </ul>
  </body>
</html>
```
After debugging things a little, I found that the function for 'entry2' never gets called. When I swap the span-tags for entry1 and entry2, only entry2 is filled and the function for entry1 is never called.

Could you imagine a reason for that? Or is there a different way to achieve what I want?

Best,
Tobias

**Comment by theseer** [comment]
That's a clear bug. And a stupid one at that.

For background: The implementation within Templado's Engine is broken for removing the Element. As the Renderer is iterating over childnodes. Removing a node from the current context breaks the loop as the tree changed.

**Comment by theseer** [comment]
Fixed.
Release will be out later today.
