### ISSUE TITLE
Apply a snippet multiple times

### ISSUE THREAD

**Issue by tduesterhus** [templado/engine#23]
Hi,

let's say, I have a webpage  with a dashboard. The dashboard should display different elements (e.g. tables, charts), etc. on one page. My first thought was, I will have a list of Models of those articles, each with the data to be rendered (ViewModel) and the Snippet the data should be rendered into. However, I did not find a way to render a list of snippets dynamically like it is possible for an array of Data with the property-Attribute. Of course it is not possible, because the (unique) ID is used to detect the target tag. Do I have to add each Element by hand to the template-xhtml file or is there an option I did not recognize? In this case I can use the typeof-attribute, but still have to add each article-template explicitly to the page (at least a placeholder for the templating).

Best Regards,
Tobi

**Comment by theseer** [comment]
Indeed Templado will refuse to re-add the same snippet when the ID of it has been seen already and the ID is part of the content added, as that would lead to an endless recursion.

I'm not sure I understand the issue at hand though: Are you trying to apply the same *object instance* of a snippet multiple times? Or are you trying to use the same xhtml markup multiple times but are going to have individual instances of snippet objects? 

As long as the ID is *not* part of the (x)html markup of the snippet, all these work like charm:

```php
<?php declare(strict_types=1);

require __DIR__ . '/autoload.php';

use Templado\Engine\SnippetListCollection;
use Templado\Engine\SimpleSnippet;
use Templado\Engine\Templado;

$dom = new DOMDocument();
$dom->loadXML('<?xml version="1.0" ?><p>hello world</p>');

$list = new SnippetListCollection();

$a = new SimpleSnippet('a', $dom->documentElement);
$list->addSnippet($a);
$list->addSnippet($a);

$list->addSnippet(new SimpleSnippet('b', $dom->documentElement));
$list->addSnippet(new SimpleSnippet('b', $dom->documentElement));

$html = Templado::parseHtmlString('<body><div id="a" /><div id="b" /></body>');
$html->applySnippets($list);

echo $html->asString();
```

__Output__:

```html
<body>
  <div id="a">
    <p>hello world</p>
    <p>hello world</p>
  </div>
  <div id="b">
    <p>hello world</p>
    <p>hello world</p>
  </div>
</body>
```

If you were creating a list of snippets programmatically, why would they have none unique IDs? If you apply a view model, you could even replace the ID of a snippet's content - in case you need to have IDs in there for some reason...

What am I missing?

**Comment by tduesterhus** [comment]
That is exactly what I need :-) I did not thought that it is possible to add a snippet to an id more than once. But that is perfect! Thanks again
