### ISSUE TITLE
Export Html-Page to TempladoSnippet

### ISSUE THREAD

**Issue by tduesterhus** [templado/engine#24]
Hi,

It is possible to export an Html instance to a SimpleSnippet. This is a great feature when it comes to the point where I want to split the rendering of a page into different sub-pages/-models/etc: I load the page as an Html instance via the static Templado-functions and apply the model to it. Then I convert it to a snippet and apply it to the base-page - works lika a charm.

But what if I want to apply a model to a snippet in templado-namespace? It would be nice to have the possibility to convert an Html instance to a TempladoSnippet. Or Maybe use the SnippetLoader and convert the snippet to an Html instance or something like that... 

Is this possible at all? The page-tag is not a valid html-tag, so conversion between TempladoSnippet and Html instance seems weird somehow

**Comment by theseer** [comment]
I'm currently prototyping / desiging Templado 5. With Templado 5, the differentiation between `Html` and `Snippet` when it comes to applying things is gone. I'm not yet sure we'll even need the conversion then, but that has yet to be seen.

**Comment by tduesterhus** [comment]
Sounds like a cool new version :-) Is there a preview on the concept?

**Comment by theseer** [comment]
Not yet. I'll publish a `concept-5.md` soon.

**Comment by theseer** [comment]
Sort of implemented in Templado 5.

The separation of Snippets and Documents got removed, exporting a selection as a new document is also supported.

This should cover all the potential use cases for this issue.
