### ISSUE TITLE
Avoid adding xmlns="http://www.w3.org/1999/xhtml" into html-tag attributes

### ISSUE THREAD

**Issue by sezersueleyman** [templado/engine#27]
Version: 4.2.1/4.2.2
Hey, 
im wondering why the xmlns="http://www.w3.org/1999/xhtml" attribute is added to my html-div tags while rendering new html files with my template.

In version 4.2.0 isnt that the case.

best regards

**Comment by theseer** [comment]
That's an attempt to fix or rather avoid issues when content gets constructed with namespaced and not namespaced nodes:

As Templado enforces XML Serialization  for HTML / HTML 5, all nodes by default are expected to be in the default namespace. If you combine DOM Elements from multiple files - as Templado does when dealing with snippets - a mix of namespaced and not namespaced nodes will lead to a mixed DOM. That causes various issues and unexpected behavior from Templado - which may be perceived as a bug. 

Given that a node does *not* require a prefix to be in a specific namespace, one cannot - after serialization - distinguish nodes not having a namespace from nodes in the default namespace:

```xml
<article xmlns="http://www.w3.org/1999/xhtml">
    <section id="with-ns" >....</section>
</article>
```

```xml
<section id="no-ns">....</div>
```

Now let's assume we inject the 2nd file into the first and serialize it to a string:

```xml
<article xmlns="http://www.w3.org/1999/xhtml">
    <section id="with-ns" >....</section>
    <section id="no-ns">....</div>
</article>
```

Give the 2nd file does *not* have a namespace ( which is **not** the same as an empty namespace!), there is no namespace declaration for the section with id `no-ns` and no prefix. But when you re-parse the 2nd string, the section node magically ended up in the default namesapce of the file (http://www.w3.org/1999/xhtml).

To avoid these issues, Templado tries to enforce namespaces.

I'm not fully convinced the current way on how Templado is doing this is actually the best way - but it's better than the alternative. Redundant xmlns attributes in a final document will get removed - even though that code is also not necessarily optimal.

**Comment by theseer** [comment]
This will no longer be an issue with Templado 5.
